services:
  cache:
    image: redis:6
    healthcheck:
      test: ["CMD-SHELL", "[ $$(redis-cli ping) = 'PONG' ]"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_interval: 5s
      start_period: 30s
    networks:
      - traefik-docker-stack_traefik_network
  directus:
    # build: https://github.com/UPSxACE/directus-xl
    image: upsxace/directus-xl:latest
    ports:
      - 8055:8055
    volumes:
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    depends_on:
      cache:
        condition: service_healthy
    # Environment variables can also be defined in a file (for example `.env`):
    env_file:
      - .env
    networks:
      - traefik-docker-stack_traefik_network
    labels:
      - traefik.enable=true
      - traefik.http.routers.web.rule=Host(`${HOSTNAME}`)
      - traefik.http.routers.web.entrypoints=websecure
      - traefik.http.routers.web.tls=true
      - traefik.http.routers.web.tls.certresolver=${CERTRESOLVER}
networks:
  traefik-docker-stack_traefik_network:
    external: true
